### ISSUE TITLE
Crash when trying to edit some exe files

### ISSUE THREAD

**Issue by insolor** [sebastianbiallas/ht#10]
A crash of the program occurs when I'm trying to edit some exe files.
ht 2.1.0, Windows 10
There is an example of a file (this is an exe file from the game UnReal World 3.30):
https://bitbucket.org/snippets/insolor/XKAX8

**Comment by sebastianbiallas** [comment]
Hi,

I cannot reproduce it on the current master branch. If you can compile HT yourself, please check whether this is fixed. Otherwise please wait for the next release.

**Comment by insolor** [comment]
@sebastianbiallas I tried to compile it, but I failed. At the moment the problem is not critical for me, so I will wait for the new release.
