### ISSUE TITLE
Can someone make a build for Ubuntu 20.04 / Linux Mint 20, please?

### ISSUE THREAD

**Issue by insolor** [sebastianbiallas/ht#26]
I tried to build it myself but failed.

**Comment by merces** [comment]
Distro maintainers can apply specific patches to programs. A package for Ubuntu 20.04 [exists](https://packages.ubuntu.com/focal/ht), therefore you can `sudo apt install ht` and the `hte` command will be available to you. But if you really want to build it from the sources, I recommend you downloading the source packages directly from the distro repositories and check instructions. I'm not a Ubuntu user, but you can also check this: [How to get source code of package using the apt command on Debian or Ubuntu](https://www.cyberciti.biz/faq/how-to-get-source-code-of-package-using-the-apt-command-on-debian-or-ubuntu/). 😉

**Comment by insolor** [comment]
@merces thanks a lot, I missed the package somehow.
