### ISSUE TITLE
Ability to customize color scheme

### ISSUE THREAD

**Issue by Inndy** [sebastianbiallas/ht#8]
![screen shot 2015-09-29 at 00 02 42](https://cloud.githubusercontent.com/assets/3402337/10141165/91202b70-663d-11e5-84a4-3b2deaab7003.png)

It looks really bad in some customized terminal color scheme. Could you add this feature?
Thanks.

**Comment by sebastianbiallas** [comment]
This is already possible (go to Windows->Options and then "palette"). Usability is not that great, though

**Comment by Inndy** [comment]
Thanks!

**Comment by nick-chandoke** [comment]
> Usability is not that great, though

1. Using kitty as my terminal on sway/wayland, it seems that when I do alt-f to select foreground, it actually selects the background palette and vice versa. Furthermore, when I use the arrow keys to change either palette's color, the change occurs, but isn't reflected in the UI until I press return to close the dialog, then press return again to re-open it.
2. Also the `window` color scheme has no effect when editing plaintext files; the default cyan is used.

Should I implement a fix for (1), or am I misunderstanding the design? (I doubt anyone uses ht for editing plaintext, so I don't think "fixing" (2) is worthwhile.)
